# Generated by Django 5.2.5 on 2025-09-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantidad_vendidos',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad vendidos'),
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
