# Generated by Django 5.2.5 on 2025-09-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_cantidad_vendidos_product_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='es_producto_dia',
            field=models.BooleanField(default=False, verbose_name='¿Producto del día?'),
        ),
    ]
