# Generated by Django 5.2.5 on 2025-11-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cantidad_vendidos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity sold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='es_producto_dia',
            field=models.BooleanField(default=False, verbose_name='Is product of the day?'),
        ),
    ]
